name: Upload to Azure Blob Storage
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: "**"
          container_name: $web
          connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
          overwrite: 'true'
